version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pm_mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - processmaker_network

  redis:
    image: redis:7-alpine
    container_name: pm_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - processmaker_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm_app
    env_file: .env
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    volumes:
      - app_data:/var/www/html/storage
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/processmaker.ini
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - processmaker_network

  webserver:
    image: nginx:1.25-alpine
    container_name: pm_webserver
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./config/nginx/processmaker.conf:/etc/nginx/conf.d/default.conf
      - app_data:/var/www/html:ro
    depends_on:
      - app
    networks:
      - processmaker_network

volumes:
  mysql_data:
  redis_data:
  app_data:

networks:
  processmaker_network:
    driver: bridge